# Generated by Django 4.2.20 on 2025-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_message_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('image', models.URLField()),
                ('date', models.DateField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_avatar', models.URLField()),
                ('author_role', models.CharField(max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
