# Generated by Django 4.2.20 on 2025-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_award_career_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Health', 'Health'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
