# Generated by Django 4.2.20 on 2025-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscriber_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='active_listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='career',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('remote', 'Remote'), ('internship', 'Internship'), ('contract', 'Contract')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='career',
            name='location',
            field=models.CharField(choices=[('Nairobi, Kenya', 'Nairobi, Kenya'), ('Mogadishu, Somalia', 'Mogadishu, Somalia'), ('Dubai, UAE', 'Dubai, UAE')], default='Nairobi, Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Politics', 'Politics'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Health', 'Health'), ('Entertainment', 'Entertainment')], default='Business', max_length=50),
        ),
    ]
