# Generated by Django 4.2.20 on 2025-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_proposalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Email where the proposal will be sent', max_length=254, null=True),
        ),
    ]
