# Generated by Django 4.2.20 on 2025-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
