# Generated by Django 4.2.20 on 2025-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_career_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mogadishu', 'Mogadishu'), ('Dubai', 'Dubai'), ('Dodoma', 'Dodoma'), ('Accra', 'Accra'), ('Addis Ababa', 'Addis Ababa'), ('Dakar', 'Dakar'), ('Kigali', 'Kigali')], default='Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='office_location',
            field=models.CharField(choices=[('Nairobi, Kenya', 'Nairobi, Kenya'), ('Mogadishu, Somalia', 'Mogadishu, Somalia'), ('Dubai, UAE', 'Dubai, UAE'), ('Dodoma, Tanzania', 'Dodoma, Tanzania'), ('Accra, Ghana', 'Accra, Ghana'), ('Ethiopia, Addis Ababa', 'Ethiopia, Addis Ababa'), ('Dakar, Senegal', 'Dakar, Senegal'), ('Kigali, Rwanda', 'Kigali, Rwanda')], default='Nairobi, Kenya', max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
