# Generated by Django 4.2.20 on 2025-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_companyinfo_address_companyinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.URLField(),
        ),
    ]
