# Generated by Django 4.2.20 on 2025-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_bio_teammember_description_teammember_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='country',
            field=models.CharField(choices=[('Global', 'Global'), ('Kenya', 'Kenya'), ('Somalia', 'Somalia'), ('Dubai', 'Dubai'), ('Ethiopia', 'Ethiopia'), ('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania'), ('Senegal', 'Senegal'), ('Ghana', 'Ghana')], default='Kenya', max_length=50),
        ),
    ]
