# Generated by Django 4.2.20 on 2025-03-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
