# Generated by Django 4.2.20 on 2025-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_career_active_listing_career_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the requester', max_length=100)),
                ('service_interest', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('digital_marketing', 'Digital Marketing'), ('graphic_design', 'Graphic Design'), ('seo', 'SEO & Analytics')], max_length=50)),
                ('details', models.TextField(help_text='Describe your requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('sent', 'Sent')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to the request', null=True)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/')),
            ],
        ),
    ]
