# Generated by Django 4.2.20 on 2025-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_partner_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='bio',
            new_name='description',
        ),
        migrations.AddField(
            model_name='teammember',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Somalia', 'Somalia'), ('Dubai', 'Dubai'), ('Ethiopia', 'Ethiopia'), ('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania'), ('Senegal', 'Senegal'), ('Ghana', 'Ghana')], default='Kenya', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, choices=[('Executive', 'Executive'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations'), ('Customer Support', 'Customer Support'), ('Software Development', 'Software Development'), ('Data Science', 'Data Science'), ('Blockchain', 'Blockchain'), ('Cybersecurity', 'Cybersecurity'), ('UI/UX Design', 'UI/UX Design'), ('DevOps', 'DevOps'), ('Graphic Design', 'Graphic Design'), ('SEO & Marketing', 'SEO & Marketing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('CEO', 'CEO'), ('CTO', 'CTO'), ('CFO', 'CFO'), ('CMO', 'CMO'), ('HR Manager', 'HR Manager'), ('Sales Lead', 'Sales Lead'), ('Marketing Lead', 'Marketing Lead'), ('Software Engineer', 'Software Engineer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Scientist', 'Data Scientist'), ('Blockchain Developer', 'Blockchain Developer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst'), ('DevOps Engineer', 'DevOps Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('Customer Support Representative', 'Customer Support Representative'), ('Graphic Designer', 'Graphic Designer'), ('SEO Expert', 'SEO Expert'), ('Social Media Marketer', 'Social Media Marketer')], max_length=50),
        ),
    ]
